import './globals.css'

export const metadata = {
  title: 'Moang App',
  description: 'Generated by Fin-tech 6',
}

export default function RootLayout({ children }) {
  return (
    <html >
      <body>
        {children}
      </body>
    </html>
  )
}
